import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import SupabaseProvider from "@/components/supabase-provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Smart Bookmarks",
  description: "Generated by  juhi",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <SupabaseProvider>
          {children}
          <Toaster
            toastOptions={{
              style: {
                background: "#1f2937", // gray-800
                color: "#fff",
                border: "1px solid #374151", // gray-700
              },
            }}
            position="bottom-center"
          />
        </SupabaseProvider>
      </body>
    </html>
  );
}
